-- UI Solution Platform - Initial Schema
-- Compatible: H2 2.x (dev) / PostgreSQL (prod)

CREATE TABLE IF NOT EXISTS usr_info (
    user_id       VARCHAR(50)  NOT NULL,
    user_nm       VARCHAR(100) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    email         VARCHAR(200),
    dept_nm       VARCHAR(100),
    use_yn        VARCHAR(1)   NOT NULL DEFAULT 'Y',
    pwd_chg_dt    DATE,
    last_login_dt TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(50),
    CONSTRAINT pk_usr_info PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS role_def (
    role_id       VARCHAR(50)  NOT NULL,
    role_nm       VARCHAR(100) NOT NULL,
    role_desc     VARCHAR(500),
    role_level    INT          NOT NULL DEFAULT 10,
    use_yn        VARCHAR(1)   NOT NULL DEFAULT 'Y',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_role_def PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS usr_role (
    user_id       VARCHAR(50)  NOT NULL,
    role_id       VARCHAR(50)  NOT NULL,
    granted_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by    VARCHAR(50),
    CONSTRAINT pk_usr_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_usr_role_user FOREIGN KEY (user_id) REFERENCES usr_info(user_id),
    CONSTRAINT fk_usr_role_role FOREIGN KEY (role_id) REFERENCES role_def(role_id)
);

CREATE TABLE IF NOT EXISTS menu_def (
    menu_id       VARCHAR(50)  NOT NULL,
    parent_id     VARCHAR(50),
    menu_nm       VARCHAR(100) NOT NULL,
    menu_url      VARCHAR(500),
    menu_icon     VARCHAR(100),
    sort_order    INT          NOT NULL DEFAULT 0,
    use_yn        VARCHAR(1)   NOT NULL DEFAULT 'Y',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_menu_def PRIMARY KEY (menu_id),
    CONSTRAINT fk_menu_parent FOREIGN KEY (parent_id) REFERENCES menu_def(menu_id)
);

CREATE TABLE IF NOT EXISTS role_menu (
    role_id       VARCHAR(50)  NOT NULL,
    menu_id       VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_role_menu PRIMARY KEY (role_id, menu_id),
    CONSTRAINT fk_role_menu_role FOREIGN KEY (role_id) REFERENCES role_def(role_id),
    CONSTRAINT fk_role_menu_menu FOREIGN KEY (menu_id) REFERENCES menu_def(menu_id)
);

CREATE TABLE IF NOT EXISTS screen_def (
    screen_id       VARCHAR(50)   NOT NULL,
    screen_nm       VARCHAR(200)  NOT NULL,
    screen_type     VARCHAR(30)   NOT NULL,
    description     VARCHAR(1000),
    api_resource    VARCHAR(200),
    layout_config   CLOB,
    button_config   CLOB,
    version         INT           NOT NULL DEFAULT 1,
    use_yn          VARCHAR(1)    NOT NULL DEFAULT 'Y',
    created_by      VARCHAR(50),
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_screen_def PRIMARY KEY (screen_id)
);

CREATE TABLE IF NOT EXISTS field_def (
    field_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    screen_id       VARCHAR(50)   NOT NULL,
    field_nm        VARCHAR(100)  NOT NULL,
    field_label     VARCHAR(200)  NOT NULL,
    field_type      VARCHAR(30)   NOT NULL,
    input_type      VARCHAR(30),
    placeholder     VARCHAR(200),
    default_value   VARCHAR(500),
    col_span        INT           NOT NULL DEFAULT 1,
    row_span        INT           NOT NULL DEFAULT 1,
    sort_order      INT           NOT NULL DEFAULT 0,
    readonly_yn     VARCHAR(1)    NOT NULL DEFAULT 'N',
    hidden_yn       VARCHAR(1)    NOT NULL DEFAULT 'N',
    code_group      VARCHAR(50),
    popup_screen_id VARCHAR(50),
    extra_config    CLOB,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_field_def PRIMARY KEY (field_id),
    CONSTRAINT fk_field_screen FOREIGN KEY (screen_id) REFERENCES screen_def(screen_id)
);

CREATE TABLE IF NOT EXISTS validation_rule (
    rule_id         BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    field_id        BIGINT        NOT NULL,
    rule_type       VARCHAR(30)   NOT NULL,
    rule_value      VARCHAR(500),
    error_msg       VARCHAR(500)  NOT NULL,
    condition_json  CLOB,
    sort_order      INT           NOT NULL DEFAULT 0,
    CONSTRAINT pk_validation_rule PRIMARY KEY (rule_id),
    CONSTRAINT fk_val_field FOREIGN KEY (field_id) REFERENCES field_def(field_id)
);

CREATE TABLE IF NOT EXISTS role_screen (
    role_id         VARCHAR(50)   NOT NULL,
    screen_id       VARCHAR(50)   NOT NULL,
    can_read        VARCHAR(1)    NOT NULL DEFAULT 'Y',
    can_create      VARCHAR(1)    NOT NULL DEFAULT 'N',
    can_update      VARCHAR(1)    NOT NULL DEFAULT 'N',
    can_delete      VARCHAR(1)    NOT NULL DEFAULT 'N',
    can_excel       VARCHAR(1)    NOT NULL DEFAULT 'N',
    can_print       VARCHAR(1)    NOT NULL DEFAULT 'N',
    CONSTRAINT pk_role_screen PRIMARY KEY (role_id, screen_id),
    CONSTRAINT fk_rs_role FOREIGN KEY (role_id) REFERENCES role_def(role_id),
    CONSTRAINT fk_rs_screen FOREIGN KEY (screen_id) REFERENCES screen_def(screen_id)
);

CREATE TABLE IF NOT EXISTS code_group (
    group_cd        VARCHAR(50)   NOT NULL,
    group_nm        VARCHAR(200)  NOT NULL,
    description     VARCHAR(500),
    use_yn          VARCHAR(1)    NOT NULL DEFAULT 'Y',
    CONSTRAINT pk_code_group PRIMARY KEY (group_cd)
);

CREATE TABLE IF NOT EXISTS code_detail (
    group_cd        VARCHAR(50)   NOT NULL,
    code_val        VARCHAR(100)  NOT NULL,
    code_nm         VARCHAR(200)  NOT NULL,
    sort_order      INT           NOT NULL DEFAULT 0,
    extra1          VARCHAR(200),
    extra2          VARCHAR(200),
    use_yn          VARCHAR(1)    NOT NULL DEFAULT 'Y',
    CONSTRAINT pk_code_detail PRIMARY KEY (group_cd, code_val),
    CONSTRAINT fk_code_group FOREIGN KEY (group_cd) REFERENCES code_group(group_cd)
);

CREATE TABLE IF NOT EXISTS component_template (
    template_id     VARCHAR(50)   NOT NULL,
    template_nm     VARCHAR(200)  NOT NULL,
    template_type   VARCHAR(50)   NOT NULL,
    description     VARCHAR(1000),
    default_config  CLOB          NOT NULL,
    thumbnail_url   VARCHAR(500),
    use_yn          VARCHAR(1)    NOT NULL DEFAULT 'Y',
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_component_template PRIMARY KEY (template_id)
);

CREATE TABLE IF NOT EXISTS sys_access_log (
    log_id          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    user_id         VARCHAR(50),
    screen_id       VARCHAR(50),
    action_type     VARCHAR(30),
    ip_address      VARCHAR(50),
    user_agent      VARCHAR(500),
    request_url     VARCHAR(500),
    result_code     VARCHAR(10),
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sys_access_log PRIMARY KEY (log_id)
);

-- ============================================================
-- Default Data
-- ============================================================

INSERT INTO role_def (role_id, role_nm, role_desc, role_level) VALUES
('SYSTEM_ADMIN', 'System Admin',  'Full platform access', 1),
('SCREEN_ADMIN', 'Screen Admin',  'Screen schema management', 2),
('DEVELOPER',    'Developer',     'API and development access', 3),
('USER',         'General User',  'Business screen access', 10);

-- Default admin account (password: Admin1234!)
INSERT INTO usr_info (user_id, user_nm, password, email) VALUES
('admin', 'System Admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'admin@company.com');

INSERT INTO usr_role (user_id, role_id, granted_by) VALUES
('admin', 'SYSTEM_ADMIN', 'system');

INSERT INTO menu_def (menu_id, parent_id, menu_nm, menu_url, menu_icon, sort_order) VALUES
('MNU001',    NULL,     'System Mgmt',   NULL,                  'SettingOutlined',  1),
('MNU001_01', 'MNU001', 'User Mgmt',     '/admin/users',        'UserOutlined',     1),
('MNU001_02', 'MNU001', 'Role Mgmt',     '/admin/roles',        'TeamOutlined',     2),
('MNU001_03', 'MNU001', 'Menu Mgmt',     '/admin/menus',        'MenuOutlined',     3),
('MNU002',    NULL,     'Screen Design', NULL,                  'AppstoreOutlined', 2),
('MNU002_01', 'MNU002', 'Screen List',   '/admin/screens',      'LayoutOutlined',   1),
('MNU002_02', 'MNU002', 'New Screen',    '/admin/screens/new',  'PlusOutlined',     2),
('MNU002_03', 'MNU002', 'Common Code',   '/admin/codes',        'TagOutlined',      3),
('MNU003',    NULL,     'Business',      NULL,                  'DatabaseOutlined', 3);

INSERT INTO role_menu (role_id, menu_id)
SELECT 'SYSTEM_ADMIN', menu_id FROM menu_def;

INSERT INTO code_group (group_cd, group_nm) VALUES
('FIELD_TYPE',  'Field Type'),
('SCREEN_TYPE', 'Screen Type'),
('VALID_TYPE',  'Validation Type'),
('USE_YN',      'Use YN');

INSERT INTO code_detail (group_cd, code_val, code_nm, sort_order) VALUES
('FIELD_TYPE', 'text',      'Text',        1),
('FIELD_TYPE', 'number',    'Number',      2),
('FIELD_TYPE', 'date',      'Date',        3),
('FIELD_TYPE', 'datetime',  'DateTime',    4),
('FIELD_TYPE', 'select',    'Select',      5),
('FIELD_TYPE', 'radio',     'Radio',       6),
('FIELD_TYPE', 'checkbox',  'Checkbox',    7),
('FIELD_TYPE', 'textarea',  'Textarea',    8),
('FIELD_TYPE', 'file',      'File',        9),
('FIELD_TYPE', 'popup',     'Popup',       10),
('SCREEN_TYPE', 'form',          'Form',          1),
('SCREEN_TYPE', 'grid',          'Grid',          2),
('SCREEN_TYPE', 'master-detail', 'Master-Detail', 3),
('SCREEN_TYPE', 'popup',         'Popup',         4),
('VALID_TYPE', 'required',  'Required',    1),
('VALID_TYPE', 'minLength', 'Min Length',  2),
('VALID_TYPE', 'maxLength', 'Max Length',  3),
('VALID_TYPE', 'min',       'Min Value',   4),
('VALID_TYPE', 'max',       'Max Value',   5),
('VALID_TYPE', 'regex',     'Regex',       6),
('VALID_TYPE', 'email',     'Email',       7),
('VALID_TYPE', 'number',    'Number Only', 8),
('USE_YN', 'Y', 'Use',    1),
('USE_YN', 'N', 'No Use', 2);

INSERT INTO component_template (template_id, template_nm, template_type, description, default_config) VALUES
('TPL_FORM_BASIC',    'Basic Form',          'form',          'Search + Input form',          '{"columns":2,"buttons":["save","reset"]}'),
('TPL_GRID_BASIC',    'Basic Grid',          'grid',          'Search + Grid list',           '{"columns":1,"hasSearch":true,"buttons":["search","excel"]}'),
('TPL_MASTER_DETAIL', 'Master-Detail',       'master-detail', 'Top grid + bottom form',       '{"masterType":"grid","detailType":"form","buttons":["search","save","delete"]}'),
('TPL_POPUP_SEARCH',  'Popup Search',        'popup',         'Search and select popup',      '{"columns":1,"hasSearch":true,"buttons":["search","select"]}');
