-- V3: Generic business data store
-- Stores form/grid data as JSON per screen, eliminating need for separate tables per screen

CREATE TABLE IF NOT EXISTS biz_data (
    data_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    screen_id     VARCHAR(50)   NOT NULL,
    project_id    VARCHAR(50),
    data_json     CLOB          NOT NULL,
    status_cd     VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_by    VARCHAR(50),
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    VARCHAR(50),
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_biz_data PRIMARY KEY (data_id),
    CONSTRAINT fk_biz_screen FOREIGN KEY (screen_id) REFERENCES screen_def(screen_id)
);

CREATE INDEX IF NOT EXISTS idx_biz_data_screen ON biz_data(screen_id, status_cd);
CREATE INDEX IF NOT EXISTS idx_biz_data_project ON biz_data(project_id, screen_id);
