CREATE TABLE uploaded_file (
    file_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_nm  VARCHAR(255) NOT NULL,
    stored_path  VARCHAR(500) NOT NULL,
    file_size    BIGINT,
    content_type VARCHAR(100),
    screen_id    VARCHAR(100),
    field_nm     VARCHAR(100),
    created_by   VARCHAR(100),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
